/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SinistresRouteImport } from './routes/sinistres'
import { Route as MonEspaceRouteImport } from './routes/mon-espace'
import { Route as EspaceClientRouteImport } from './routes/espace-client'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssuranceVoyageRouteImport } from './routes/assurance-voyage'
import { Route as AssuranceVieRouteImport } from './routes/assurance-vie'
import { Route as AssuranceSanteRouteImport } from './routes/assurance-sante'
import { Route as AssuranceHabitationRouteImport } from './routes/assurance-habitation'
import { Route as AssuranceAutoRouteImport } from './routes/assurance-auto'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsGestionRisquesRouteImport } from './routes/solutions.gestion-risques'
import { Route as SolutionsAssurancePersonnesRouteImport } from './routes/solutions.assurance-personnes'
import { Route as SolutionsAssuranceMaladieRouteImport } from './routes/solutions.assurance-maladie'
import { Route as SolutionsAssuranceIardtRouteImport } from './routes/solutions.assurance-iardt'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SinistresRoute = SinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceRoute = MonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceClientRoute = EspaceClientRouteImport.update({
  id: '/espace-client',
  path: '/espace-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceVoyageRoute = AssuranceVoyageRouteImport.update({
  id: '/assurance-voyage',
  path: '/assurance-voyage',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceVieRoute = AssuranceVieRouteImport.update({
  id: '/assurance-vie',
  path: '/assurance-vie',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceSanteRoute = AssuranceSanteRouteImport.update({
  id: '/assurance-sante',
  path: '/assurance-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceHabitationRoute = AssuranceHabitationRouteImport.update({
  id: '/assurance-habitation',
  path: '/assurance-habitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceAutoRoute = AssuranceAutoRouteImport.update({
  id: '/assurance-auto',
  path: '/assurance-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsGestionRisquesRoute = SolutionsGestionRisquesRouteImport.update({
  id: '/solutions/gestion-risques',
  path: '/solutions/gestion-risques',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAssurancePersonnesRoute =
  SolutionsAssurancePersonnesRouteImport.update({
    id: '/solutions/assurance-personnes',
    path: '/solutions/assurance-personnes',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAssuranceMaladieRoute =
  SolutionsAssuranceMaladieRouteImport.update({
    id: '/solutions/assurance-maladie',
    path: '/solutions/assurance-maladie',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAssuranceIardtRoute = SolutionsAssuranceIardtRouteImport.update({
  id: '/solutions/assurance-iardt',
  path: '/solutions/assurance-iardt',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/agences': typeof AgencesRoute
  '/assurance-auto': typeof AssuranceAutoRoute
  '/assurance-habitation': typeof AssuranceHabitationRoute
  '/assurance-sante': typeof AssuranceSanteRoute
  '/assurance-vie': typeof AssuranceVieRoute
  '/assurance-voyage': typeof AssuranceVoyageRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/espace-client': typeof EspaceClientRoute
  '/mon-espace': typeof MonEspaceRoute
  '/sinistres': typeof SinistresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/solutions/assurance-iardt': typeof SolutionsAssuranceIardtRoute
  '/solutions/assurance-maladie': typeof SolutionsAssuranceMaladieRoute
  '/solutions/assurance-personnes': typeof SolutionsAssurancePersonnesRoute
  '/solutions/gestion-risques': typeof SolutionsGestionRisquesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/agences': typeof AgencesRoute
  '/assurance-auto': typeof AssuranceAutoRoute
  '/assurance-habitation': typeof AssuranceHabitationRoute
  '/assurance-sante': typeof AssuranceSanteRoute
  '/assurance-vie': typeof AssuranceVieRoute
  '/assurance-voyage': typeof AssuranceVoyageRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/espace-client': typeof EspaceClientRoute
  '/mon-espace': typeof MonEspaceRoute
  '/sinistres': typeof SinistresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/solutions/assurance-iardt': typeof SolutionsAssuranceIardtRoute
  '/solutions/assurance-maladie': typeof SolutionsAssuranceMaladieRoute
  '/solutions/assurance-personnes': typeof SolutionsAssurancePersonnesRoute
  '/solutions/gestion-risques': typeof SolutionsGestionRisquesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/agences': typeof AgencesRoute
  '/assurance-auto': typeof AssuranceAutoRoute
  '/assurance-habitation': typeof AssuranceHabitationRoute
  '/assurance-sante': typeof AssuranceSanteRoute
  '/assurance-vie': typeof AssuranceVieRoute
  '/assurance-voyage': typeof AssuranceVoyageRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/espace-client': typeof EspaceClientRoute
  '/mon-espace': typeof MonEspaceRoute
  '/sinistres': typeof SinistresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/solutions/assurance-iardt': typeof SolutionsAssuranceIardtRoute
  '/solutions/assurance-maladie': typeof SolutionsAssuranceMaladieRoute
  '/solutions/assurance-personnes': typeof SolutionsAssurancePersonnesRoute
  '/solutions/gestion-risques': typeof SolutionsGestionRisquesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/agences'
    | '/assurance-auto'
    | '/assurance-habitation'
    | '/assurance-sante'
    | '/assurance-vie'
    | '/assurance-voyage'
    | '/contact'
    | '/devis'
    | '/espace-client'
    | '/mon-espace'
    | '/sinistres'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/solutions/assurance-iardt'
    | '/solutions/assurance-maladie'
    | '/solutions/assurance-personnes'
    | '/solutions/gestion-risques'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/agences'
    | '/assurance-auto'
    | '/assurance-habitation'
    | '/assurance-sante'
    | '/assurance-vie'
    | '/assurance-voyage'
    | '/contact'
    | '/devis'
    | '/espace-client'
    | '/mon-espace'
    | '/sinistres'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/solutions/assurance-iardt'
    | '/solutions/assurance-maladie'
    | '/solutions/assurance-personnes'
    | '/solutions/gestion-risques'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/agences'
    | '/assurance-auto'
    | '/assurance-habitation'
    | '/assurance-sante'
    | '/assurance-vie'
    | '/assurance-voyage'
    | '/contact'
    | '/devis'
    | '/espace-client'
    | '/mon-espace'
    | '/sinistres'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/solutions/assurance-iardt'
    | '/solutions/assurance-maladie'
    | '/solutions/assurance-personnes'
    | '/solutions/gestion-risques'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRouteWithChildren
  AgencesRoute: typeof AgencesRoute
  AssuranceAutoRoute: typeof AssuranceAutoRoute
  AssuranceHabitationRoute: typeof AssuranceHabitationRoute
  AssuranceSanteRoute: typeof AssuranceSanteRoute
  AssuranceVieRoute: typeof AssuranceVieRoute
  AssuranceVoyageRoute: typeof AssuranceVoyageRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  EspaceClientRoute: typeof EspaceClientRoute
  MonEspaceRoute: typeof MonEspaceRoute
  SinistresRoute: typeof SinistresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsAssuranceIardtRoute: typeof SolutionsAssuranceIardtRoute
  SolutionsAssuranceMaladieRoute: typeof SolutionsAssuranceMaladieRoute
  SolutionsAssurancePersonnesRoute: typeof SolutionsAssurancePersonnesRoute
  SolutionsGestionRisquesRoute: typeof SolutionsGestionRisquesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinistres': {
      id: '/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof SinistresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace': {
      id: '/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof MonEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-client': {
      id: '/espace-client'
      path: '/espace-client'
      fullPath: '/espace-client'
      preLoaderRoute: typeof EspaceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-voyage': {
      id: '/assurance-voyage'
      path: '/assurance-voyage'
      fullPath: '/assurance-voyage'
      preLoaderRoute: typeof AssuranceVoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-vie': {
      id: '/assurance-vie'
      path: '/assurance-vie'
      fullPath: '/assurance-vie'
      preLoaderRoute: typeof AssuranceVieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-sante': {
      id: '/assurance-sante'
      path: '/assurance-sante'
      fullPath: '/assurance-sante'
      preLoaderRoute: typeof AssuranceSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-habitation': {
      id: '/assurance-habitation'
      path: '/assurance-habitation'
      fullPath: '/assurance-habitation'
      preLoaderRoute: typeof AssuranceHabitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-auto': {
      id: '/assurance-auto'
      path: '/assurance-auto'
      fullPath: '/assurance-auto'
      preLoaderRoute: typeof AssuranceAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/gestion-risques': {
      id: '/solutions/gestion-risques'
      path: '/solutions/gestion-risques'
      fullPath: '/solutions/gestion-risques'
      preLoaderRoute: typeof SolutionsGestionRisquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/assurance-personnes': {
      id: '/solutions/assurance-personnes'
      path: '/solutions/assurance-personnes'
      fullPath: '/solutions/assurance-personnes'
      preLoaderRoute: typeof SolutionsAssurancePersonnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/assurance-maladie': {
      id: '/solutions/assurance-maladie'
      path: '/solutions/assurance-maladie'
      fullPath: '/solutions/assurance-maladie'
      preLoaderRoute: typeof SolutionsAssuranceMaladieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/assurance-iardt': {
      id: '/solutions/assurance-iardt'
      path: '/solutions/assurance-iardt'
      fullPath: '/solutions/assurance-iardt'
      preLoaderRoute: typeof SolutionsAssuranceIardtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
  }
}

interface ActualitesRouteChildren {
  ActualitesSlugRoute: typeof ActualitesSlugRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesSlugRoute: ActualitesSlugRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRouteWithChildren,
  AgencesRoute: AgencesRoute,
  AssuranceAutoRoute: AssuranceAutoRoute,
  AssuranceHabitationRoute: AssuranceHabitationRoute,
  AssuranceSanteRoute: AssuranceSanteRoute,
  AssuranceVieRoute: AssuranceVieRoute,
  AssuranceVoyageRoute: AssuranceVoyageRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  EspaceClientRoute: EspaceClientRoute,
  MonEspaceRoute: MonEspaceRoute,
  SinistresRoute: SinistresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsAssuranceIardtRoute: SolutionsAssuranceIardtRoute,
  SolutionsAssuranceMaladieRoute: SolutionsAssuranceMaladieRoute,
  SolutionsAssurancePersonnesRoute: SolutionsAssurancePersonnesRoute,
  SolutionsGestionRisquesRoute: SolutionsGestionRisquesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
